version: "3.3"
services:
  web:
    build: .
    container_name: rust
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 4000:4000
    networks:
      - consul
    command: bash -c "cargo build && cargo run"
networks:
  consul:
    external: true
